version: "3"
services:
  frontend:
    image: neemogu/movinf-frontend:latest
    container_name: frontend
    ports:
      - '80:80'
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
      - 'init.sql:/docker-entrypoint-initdb.d/init.sql'
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=*****
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
  backend:
    image: neemogu/movinf-backend:latest
    network_mode: bridge
    container_name: movinf-backend
    expose:
      - 8080
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data: