version: "3"
services:
  frontend:
    image: neemogu/movinf-frontend:latest
    container_name: frontend
    ports:
      - '80:80'
  db:
    image: postgres:latest
    network_mode: bridge
    container_name: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=8ckh9vd2
      - POSTGRES_USER=movinf
    restart: unless-stopped
  backend:
    image: neemogu/movinf-backend:latest
    network_mode: bridge
    container_name: movinf-backend
    expose:
      - 8080
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/movinf
      - SPRING_DATASOURCE_USERNAME=movinf
      - SPRING_DATASOURCE_PASSWORD=8ckh9vd2
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped
    depends_on: 
      - db
    links:
      - db